# Generated by Django 3.2.13 on 2022-11-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20221116_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='movies.Genre'),
        ),
    ]
