# Generated by Django 3.2.13 on 2022-11-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20221122_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='like_users',
        ),
    ]
