# Generated by Django 3.2.13 on 2022-11-17 01:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_auto_20221117_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
