# Generated by Django 3.2.13 on 2022-11-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_adult',
            field=models.BooleanField(null=True),
        ),
    ]
