# Generated by Django 3.2.13 on 2022-11-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_followings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_adult',
            field=models.BooleanField(default=False),
        ),
    ]
